spring.application.name=EmployeeRegisterApplication

server.port=${PORT:10000}

spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:29877/railway
spring.datasource.username=root
spring.datasource.password=nrVofFEEUmeWbtPGtIVEFwZcvbaSBadU

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
